# Generated by Django 4.1 on 2022-09-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('shift_duration', models.TimeField()),
            ],
        ),
    ]
