# Generated by Django 4.1 on 2022-09-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_on_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_on_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_on_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_on_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_on_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_on_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=5)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'ordering': ['shift_name'],
            },
        ),
    ]
