# Generated by Django 4.1 on 2022-09-02 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shift_shift_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
